<a href="https://colab.research.google.com/github/saranyaece30111998-analyst/DATA-TRANSFORMATION-USING-PANDAS/blob/main/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# data transformation using pandas

In [ ]:
#  reading an Excel file directly from Google Drive in Google Colab:
# Import Google Drive module
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Import pandas
import pandas as pd

# Give Excel file path from Google Drive
# Replace file name/path with your actual file
file_path ='/content/drive/MyDrive/Employee_data.csv'



# Read Excel file
df = pd.read_csv(file_path)
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me
...,...,...,...,...,...,...,...,...,...,...,...
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [ ]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car,Useless_Col
0,1000,hannah,NaN,finance,$Developer$,"Sep 16, 2023",70k,poor,11-11-2025 22:00,0,NaN
1,1001,ivan,30.0,it,Sr@Analyst,29-Aug-22,"45,500",excellent,07-11-2025 05:00,0,remove_me
2,1002,frank,32.0,IT,Intern*,19-04-2023,70k,good,NaN,1,remove_me
3,1003,david,NaN,IT,Data-Scientist,02/14/23,40000,poor,31-10-2025 19:00,NaN,remove_me
4,1004,mike,28.0,finanace,$Developer$,16-Aug-19,60000,NaN,NaN,1,remove_me
...,...,...,...,...,...,...,...,...,...,...,...
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1,NaN
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0,remove_me
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1,remove_me
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0,NaN
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No,remove_me

In [ ]:
# Check missing values in each column
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Employee_ID         0
Name                0
Age                31
Department          0
Position            0
Joining_Date        0
Salary             17
Feedback           63
Last_Login_Time    55
Has_Car            19
Useless_Col        93
dtype: int64

Data quality checks

Data Cleaning

In [ ]:
#drop a single column
df.drop('Useless_Col', axis=1, inplace=True)

duplicated removal

In [ ]:
# Returns the total number of duplicated rows
df.duplicated().sum()

np.int64(5)

In [ ]:
#Display Duplicate Rows
df[df.duplicated()]

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No

In [ ]:
#Display All Occurrences of Duplicates

df[df.duplicated(keep=False)]

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
15,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
30,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
95,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
128,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No
158,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0
200,1095,tina,35.0,HR,Intern*,07-02-2022,60000,NaN,07-11-2025 04:00,1
201,1015,grace,32.0,FINANCE,$Developer$,"Nov 14, 2021",NaN,average,07-11-2025 20:00,0
202,1030,STEVE,32.0,HR,$Developer$,04-03-2018,"65,000",good,04-11-2025 16:00,1
203,1158,kevin,24.0,it,Intern*,16-May-23,40000,NaN,10-11-2025 21:00,0
204,1128,david,30.0,IT,$Developer$,06-02-2023,"45,500",NaN,07-11-2025 21:00,No

In [ ]:
# Remove duplicates
df.drop_duplicates(inplace=True)

# name column cleaning

In [ ]:
df['Name']=df['Name'].str.title().str.strip()

AGE COLUMN

In [ ]:
df['Age'].fillna((df['Age'].mean()), inplace=True)

/tmp/ipykernel_579/1715186124.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna((df['Age'].mean()), inplace=True)

DEPARTMENT COLUMN

In [ ]:
# finf unique value in department
df['Department'].unique()

array(['Finance', 'IT', 'HR', 'Sales', 'Marketing'], dtype=object)

In [ ]:
# find value count of department
df['Department'].value_counts()

Department
Finance      61
IT           47
HR           41
Sales        27
Marketing    24
Name: count, dtype: int64

In [ ]:
# upper casing all names
df['Department']=df['Department'].str.upper()

In [ ]:
# replace values
df['Department'].replace('FINANACE','Finance',inplace=True)

/tmp/ipykernel_579/3464717638.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].replace('FINANACE','Finance',inplace=True)

In [ ]:
# replace multiple values
df['Department'].replace({'FINANCE':'Finance',
                          'MARKETING':'Marketing',
                          'SALES':'Sales'},inplace=True)

/tmp/ipykernel_579/75262796.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Department'].replace({'FINANCE':'Finance',

# position column

In [ ]:
df['Position'].unique()

array([' Developer ', 'Sr Analyst', 'Intern ', 'Data Scientist',
       ' Manager', ' Clerk', ' Analyst'], dtype=object)

In [ ]:
# Remove any special characters like !, @, #, etc.
df['Position']=df['Position'].str.replace(r'[^a-zA-Z ]',' ', regex=True)

# salary column

In [ ]:
df['Salary'].unique()

array([70000., 45500., 40000., 60000., 55000., 65000., 52500., 50000.,
       67500.])

In [ ]:
#DISPLAYING SALARY
df["Salary"].value_counts(dropna = False)

Salary
60000.0    37
40000.0    34
55000.0    31
45500.0    30
70000.0    23
65000.0    23
50000.0    19
52500.0     2
67500.0     1
Name: count, dtype: int64

In [ ]:
df["Salary"] = df['Salary'].str. replace("70k","70000").str.replace(",","")

In [ ]:
# changeing data types
df["Salary"]= df["Salary"].astype(float)

In [ ]:
# Hierarchical imputation
# Level 1: Department + Position mean
dept_pos_mean = df.groupby(['Department','Position'])['Salary'].transform('median')

# # # # Level 2: Department mean
dept_mean = df.groupby('Department')['Salary'].transform('mean')

# # # Level 3: Overall mean
overall_mean = df['Salary'].mean()

# Hierarchical imputation
df['Salary'] = (df['Salary'].fillna(dept_pos_mean).fillna(dept_mean).fillna(overall_mean))

Feedback column

In [ ]:
df["Feedback"].unique()

array(['Poor', 'Excellent', 'Good', 'Average'], dtype=object)

In [ ]:
df["Feedback"].value_counts()

Feedback
Average      115
Poor          31
Good          29
Excellent     25
Name: count, dtype: int64

In [ ]:
df["Feedback"] = df['Feedback'].str. replace("?","Average").str.title()

In [ ]:
df["Feedback"] = df['Feedback'].fillna("Average")

# has car

In [ ]:
df["Has_Car"].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
df['Has_Car'].replace({
    '0': 'No',
    '1': 'Yes'
}, inplace=True)

/tmp/ipykernel_579/1435213368.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Has_Car'].replace({

In [ ]:
df["Has_Car"] = df['Has_Car'].fillna("No")

In [ ]:
df['Employee_ID'] = df['Employee_ID'].astype(str)

# date times

In [ ]:
df.dtypes

Employee_ID         object
Name                object
Age                float64
Department          object
Position            object
Joining_Date        object
Salary             float64
Feedback            object
Last_Login_Time     object
Has_Car             object
dtype: object

In [ ]:
df.isnull().sum()

Employee_ID        0
Name               0
Age                0
Department         0
Position           0
Joining_Date       0
Salary             0
Feedback           0
Last_Login_Time    0
Has_Car            0
dtype: int64

In [ ]:
# join ing data
df['Joining_Date'] = pd.to_datetime(df['Joining_Date'],format="mixed",errors='coerce',dayfirst=True)

In [ ]:
df['Last_Login_Time'] = pd.to_datetime(df['Last_Login_Time'],format="mixed",errors='coerce',dayfirst=True)

In [ ]:
df["Last_Login_Time"]=df['Last_Login_Time'].fillna(df['Last_Login_Time'].mode()[0])

In [ ]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,37.733728,Finance,Developer,2023-09-16,70000.0,Poor,2025-11-11 22:00:00,No
1,1001,Ivan,30.000000,IT,Sr Analyst,2022-08-29,45500.0,Excellent,2025-11-07 05:00:00,No
2,1002,Frank,32.000000,IT,Intern,2023-04-19,70000.0,Good,2025-11-02 18:00:00,Yes
3,1003,David,37.733728,IT,Data Scientist,2023-02-14,40000.0,Poor,2025-10-31 19:00:00,No
4,1004,Mike,28.000000,Finance,Developer,2019-08-16,60000.0,Average,2025-11-02 18:00:00,Yes
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.000000,Marketing,Sr Analyst,2020-07-07,60000.0,Poor,2025-11-07 09:00:00,Yes
196,1196,Paula,26.000000,Finance,Analyst,2021-05-12,45500.0,Average,2025-11-08 16:00:00,No
197,1197,Alice,30.000000,Finance,Data Scientist,2022-02-14,65000.0,Good,2025-11-11 22:00:00,No
198,1198,Mike,32.000000,IT,Clerk,2021-02-15,45500.0,Average,2025-11-02 18:00:00,Yes
199,1199,Kevin,28.000000,IT,Developer,2020-07-15,40000.0,Average,2025-11-03 16:00:00,Yes

In [ ]:
df.shape

(200, 10)

In [ ]:
df['Age'] = df['Age'].round()

In [ ]:
df

,Employee_ID,Name,Age,Department,Position,Joining_Date,Salary,Feedback,Last_Login_Time,Has_Car
0,1000,Hannah,37.733728,Finance,Developer,2023-09-16,70000.0,Poor,2025-11-11 22:00:00,No
1,1001,Ivan,30.000000,IT,Sr Analyst,2022-08-29,45500.0,Excellent,2025-11-07 05:00:00,No
2,1002,Frank,32.000000,IT,Intern,2023-04-19,70000.0,Good,2025-11-02 18:00:00,Yes
3,1003,David,37.733728,IT,Data Scientist,2023-02-14,40000.0,Poor,2025-10-31 19:00:00,No
4,1004,Mike,28.000000,Finance,Developer,2019-08-16,60000.0,Average,2025-11-02 18:00:00,Yes
...,...,...,...,...,...,...,...,...,...,...
195,1195,Nina,26.000000,Marketing,Sr Analyst,2020-07-07,60000.0,Poor,2025-11-07 09:00:00,Yes
196,1196,Paula,26.000000,Finance,Analyst,2021-05-12,45500.0,Average,2025-11-08 16:00:00,No
197,1197,Alice,30.000000,Finance,Data Scientist,2022-02-14,65000.0,Good,2025-11-11 22:00:00,No
198,1198,Mike,32.000000,IT,Clerk,2021-02-15,45500.0,Average,2025-11-02 18:00:00,Yes
199,1199,Kevin,28.000000,IT,Developer,2020-07-15,40000.0,Average,2025-11-03 16:00:00,Yes

In [ ]:
df.dtypes

Employee_ID                object
Name                       object
Age                       float64
Department                 object
Position                   object
Joining_Date       datetime64[ns]
Salary                    float64
Feedback                   object
Last_Login_Time    datetime64[ns]
Has_Car                    object
dtype: object